### ISSUE TITLE
Before you register all these, make sure your Trading client actually stands up correctly 

### ISSUE THREAD

**Issue by ntindle** [danikhan632/Auto-GPT-AlpacaTrader-Plugin#1]
https://github.com/danikhan632/Auto-GPT-AlpacaTrader-Plugin/blob/e4258e6d80b0547b3c12be224f2ed1869cb17b10/src/auto_gpt_alpacatrader_plugin/__init__.py#L31

**Comment by danikhan632** [comment]
it now fully works
