### ISSUE TITLE
Cant Instantiate Abstract Class

### ISSUE THREAD

**Issue by mrsithz** [danikhan632/Auto-GPT-AlpacaTrader-Plugin#11]
TypeError: Can't instantiate abstract class AutoGPTAlpacaTraderPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

Getting this error from v 3 to 4.  Stand alone or docker.  Thanks

**Comment by danikhan632** [comment]
just fixed thanks for the heads up
